xpos334/xpos334/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {
            categoryService = _categoryService;
            variantService = _variantService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.currentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.NameCategory.ToLower().Contains(searchString.ToLower())
                || a.Description!.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> ListCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = ListCategory;

            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string name, int id, int idCategory)
        {
            bool isExist = await variantService.CheckByName(name, id, idCategory);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

            List<TblCategory> ListCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = ListCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await variantService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task <IActionResult> Detail (int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task <IActionResult> SureDelete (int id)
        {
            VMResponse respon = await variantService.Delete(id);

            if (respon.Success)
            {
                return Json(new {dataRespon = respon});
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MultipleDelete(List<int> ListId)
        {
            List<string> ListName = new List<string>();
            foreach (int item in ListId)
            {
                VMTblVariant data = await variantService.GetDataById(item);
                ListName.Add(data.NameVariant);
            }
            
            ViewBag.ListName = ListName;
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> SureMultipleDelete(List<int> ListId)
        {
            VMResponse respon = await variantService.MultipleDelete(ListId); 
            if (respon.Success) 
            {
                return Json(new {dataRespon=respon});
            }
            return RedirectToAction("Index");
        }
    }
}

xpos334/xpos334/Controllers/VariantTryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class VariantTryController : Controller
    {
        private readonly XPOS_334Context db;
        private readonly CategoryTryService categoryService;
        private readonly VariantTryService variantTryService;

        private static VMPage page = new VMPage();

        public VariantTryController(XPOS_334Context _db)
        {
            db = _db;
            categoryService = new CategoryTryService(db);
            variantTryService = new VariantTryService(db);
        }

        public IActionResult Index(VMPage pg)
        {
            ViewBag.idSort = string.IsNullOrEmpty(pg.sortOrder) ? "id_desc" : "";
            ViewBag.nameSort = pg.sortOrder == "name" ? "name_desc" : "name";
            ViewBag.CurrentSort = pg.sortOrder;
            ViewBag.currentShowData = pg.showData;

            if (pg.searchString != null)
            {
                pg.pageNumber = 1;
            }
            else
            {
                pg.searchString = pg.currentFilter;
            }

            ViewBag.CurrentFilter = pg.currentFilter;

            List<VMTblVariant> dataView = variantTryService.GetAllData();

            if (!string.IsNullOrEmpty(pg.searchString))
            {
                dataView = dataView.Where(a => a.NameVariant.ToLower().Contains(pg.searchString.ToLower())
                || a.NameCategory.ToLower().Contains(pg.searchString.ToLower())).ToList();
            }

            switch (pg.sortOrder)
            {
                case "name_desc":
                    dataView = dataView.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                case "name":
                    dataView = dataView.OrderBy(a => a.NameVariant).ToList();
                    break;
                case "id_desc":
                    dataView = dataView.OrderByDescending(a => a.Id).ToList();
                    break;
                default:
                    dataView = dataView.OrderBy(a => a.Id).ToList();
                    break;

            }

            int pageSize = pg.showData ?? 3;

            page = pg;


            return View(PaginatedList<VMTblVariant>.CreateAsync(dataView, pg.pageNumber ?? 1, pageSize));
        }

        public IActionResult Create()
        {
            VMTblVariant dataView = new VMTblVariant();
            ViewBag.DropdownCategory = categoryService.GetAllData();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            respon = variantTryService.Create(dataView);

            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            ViewBag.DropdownCategory = categoryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            ViewBag.DropdownCategory = categoryService.GetAllData();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            respon = variantTryService.Edit(dataView);

            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            ViewBag.DropdownCategory = categoryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            return View(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]

        public IActionResult Delete(VMTblVariant dataView)
        {
            VMResponse respon = variantTryService.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            return View(respon.Entity);
        }
    }
}

xpos334/xpos334/Views/Variant/Create.cshtml
@using xpos334.viewmodels;
@model VMTblVariant
@{
    ViewData["Title"] = "Create Variant";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                    <span id="validate_NameVariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory,"Id","NameCategory"),
                    "--Select Category--",
                    new{@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>


    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            NameVariant: {
                required: "Please fill name category",
                minlength: "The name must consist of at least 3 character",
            }
        },
        submitHandler: function (form) {
            //debugger
            //console.log(form)
            var dataForm = $(form).serialize();

            var name = $("#NameVariant").val();
            var id = 0
            var idCategory = $("#IdCategory").val();

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get",
                data: { name: name, id: id, idCategory: idCategory },
                datatype: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameVariant").text("Name Variant is already exist")
                        return true;
                    }
                    else {
                        fungsisubmit(dataForm)
                    }
                }
            })

        }
    })

    function fungsisubmit(dataParam) {
        $.ajax({
            url: "/Variant/Create",
            type: "post",
            data: dataParam,
            datatype: "json",
            success: function (respon) {
                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }
            }
        })
    }

</script>

xpos334/xpos334/Views/Variant/Delete.cshtml
@using xpos334.viewmodels;
@model VMTblVariant
@{
    ViewData["Title"] = "Delete Variant";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">

            <input type="hidden" id="Id" name="Id" value="@Model.Id" />

            <h3>Are you sure for delete @Model.NameVariant ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Variant" asp-action="Index" class="btn btn-secondary">No</a>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            //var dataParam = $(form).serialize()
            var id = $("#Id").val()

            $.ajax({
                url: "/Variant/SureDelete",
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#my_modal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })

        }
    })
</script>

xpos334/xpos334/Views/Variant/Detail.cshtml
@using xpos334.viewmodels;
@model VMTblVariant
@{
    ViewData["Title"] = "Detail Variant";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>


            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>

                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <a class="btn btn-light" asp-controller="VariantTry" asp-action="Index">Back to List</a>
                </div>
            </div>

    </div>
</div>

xpos334/xpos334/Views/Variant/Edit.cshtml
﻿@using xpos334.viewmodels;
@model VMTblVariant
@{
    ViewData["Title"] = "Edit Variant";
}

<div class="card">
    <div class="card-body">

        @*<div class="h4 mb-4">@ViewData["Title"]</div>*@
        <div class="card-title">@ViewData["Title"]</div>


        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                    <span id="validate_NameVariant" class="text-danger"></span>

                </div>
            </div>
            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Nama Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                    "---Pilih Category---",
                    new { @class = "form-control"}
                    )
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary" id="fungsisubmit">Submit</button>
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>



    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            NameVariant: {
                required: "Please Fill Name Variant",
                minlength: "The name consist of at least 3 characters",
            },
            IdCategory: "Please select category"
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize();

            var name = $("#NameVariant").val()
            var id = $("#Id").val()
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get",
                data: { name: name, id: id, idCategory: idCategory },
                datatype: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameVariant").text("Name Variant is already exist")
                        return true;
                    }
                    else {
                        fungsisubmit(dataForm)
                    }
                }
            })
        }
    })

    function fungsisubmit(dataParam) {
        $.ajax({
            url: "/Variant/Edit",
            type: "post",
            data: dataParam,
            datatype: "json",
            success: function (respon) {
                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }
            }
        })
    }
</script>

xpos334/xpos334/Views/Variant/Index.cshtml
@using xpos334.viewmodels;


@model PaginatedList<VMTblVariant>

@{
    ViewData["Title"] = "Variant";
}

<div class="card">
    <div class="card-body">

        <h1 class="card-title">@ViewData["Title"]</h1>

        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">

                    <button id="btn_create" class="btn btn-primary">Create</button>

                    <button id="btn_multiple_delete" class="btn btn-danger" disabled>Hapus Multiple</button>
                    
                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">

                    <div class="input-group w-100">
                        <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search.." />
                        <div class="input-group-prepend">
                            <button type="submit" class="input-group-text" title="search">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                        <div class="input-group-prepend">
                            <a class="input-group-text" asp-action="Index" title="reset">
                                <i class="fas fa-redo"></i>
                            </a>

                        </div>
                    </div>
                    </form>

                </div>
            </div>
        </div>

        <table class="table table-hover mb-3">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageSize="@ViewBag.currentPageSize">
                            Name Variant
                        </a>
                    </th>
                    <th>Name Category</th>
                    <th>Description</th>
                    <th>Is Delete</th>
                    <th>Create Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><input type="checkbox" onchange="selectedItem()" class="mychecked" value="@item.Id"/></td>
                            <td>@item.NameVariant</td>
                            <td>@item.NameCategory</td>
                            <td>@item.Description</td>
                            <td>
                                @if(item.IsDelete == true)
                                {
                                    <input type="checkbox" checked disabled />
                                }
                                else
                                {
                                    <input type="checkbox" disabled/>

                                }
                            </td>
                            <td>@item.CreateDate.ToString("dddd, dd MMMM yyyy HH:mm:ss");</td>
                            <td>
                                <a class="btn btn-warning btn_edit" style="color:white" dataid="@item.Id">Edit</a>
                                <a class="btn btn-secondary btn_detail" style="color:white" dataid="@item.Id">Detail</a>
                                <a class="btn btn-danger btn_delete" style="color:white" dataid="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Data not found</td>
                    </tr>
                }


            </tbody>

        </table>
    </div>

    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <div class="row">
            <div class="col-2">
                <form asp-action="Index" id="form_pagesize">
                    <select name="PageSize" id="PageSize" class="form-control">
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                    </select>
                </form>
            </div>
            <div class="col-10">
                Page @Model.PageIndex of @Model.TotalPages
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @nextDisabled">
                    Next
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @prevDisabled">
                    Previous
                </a>
            </div>
        </div>


    </div>
</div>


<script>

    var ListId = []
    
    function selectedItem(){
        var mychecked = $(".mychecked")
        ListId = []
        for (var i = 0; i < mychecked.length; i++) {
            if (mychecked[i].checked) {
                ListId.push(mychecked[i].value)
            }
        }

        if (ListId.length > 0) {
            $("#btn_multiple_delete").attr("disabled", false)
        }
        else {
            $("#btn_multiple_delete").attr("disabled", true)
        }
    }

    $("#btn_multiple_delete").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/MultipleDelete", { ListId : ListId })
        $("#my_modal").modal("show")

    })




    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Edit?id=" + id)
        $("#my_modal").modal("show")
    })

    $(".btn_detail").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Detail?id=" + id)
        $("#my_modal").modal("show")
    })

    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Variant/Delete?id=" + id)
        $("#my_modal").modal("show")
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)

    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })




</script>

xpos334/xpos334/Views/Variant/MultipleDelete.cshtml
@{
    ViewData["Title"] = "Multiple Delete Variant";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureMultipleDelete" method="post" id="form_delete">

            <h3>Are you sure for delete ?</h3>
            @foreach (var item in ViewBag.ListName)
            {
                <h4>@item</h4>
            }

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Variant" asp-action="Index" class="btn btn-secondary">No</a>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
            $.ajax({
                url: "/Variant/SureMultipleDelete",
                type: "post",
                data: { ListId: ListId },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#my_modal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })

        }
    })
</script>